import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { getCandidateList } from "services/candidates";
import { CandidateType } from "types/candidate";
import styles from "styles/Home.module.css";
import Candidate from "components/candidate";

const Home: NextPage = () => {
  const [candidatesList, setCandidatesList] = useState<CandidateType[]>([]);
  useEffect(() => {
    getCandidateList<CandidateType[]>().then(setCandidatesList);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <img alt="Softvision" src="logo.png" width={320} />
        <h1 className={styles.title}>Lets get this party started</h1>
        <section className={styles.grid}>
          <article className={styles.card}>
            <h2>Entrevista Inicial</h2>
            <ul className={styles.list}>
              {candidatesList.map((candidate) => (
                <Candidate candidate={candidate} key={candidate.id} />
              ))}
            </ul>
          </article>
          <article className={styles.card}>
            <h2>Entrevista Técnica</h2>
          </article>
          <article className={styles.card}>
            <h2>Oferta</h2>
          </article>
          <article className={styles.card}>
            <h2>Asignación</h2>
          </article>
          <article className={styles.card}>
            <h2>Rechazo</h2>
          </article>
        </section>
      </main>
    </div>
  );
};

export default Home;
