import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <img alt="Softvision" src="logo.png" width={320} />
        <h1 className={styles.title}>Lets get this party started</h1>
      </main>
    </div>
  );
};

export default Home;
